language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode
  - jruby-head
notifications:
  recipients:
    - ricny046@gmail.com
before_install:
  - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex --yes
  - sudo apt-get update -qq
  - sudo apt-get install pdf2htmlex libxslt-dev libxml2-dev